stages:
- stage: A
  jobs:
  - job: myJob
    displayName: string  # friendly name to display in the UI
    timeoutInMinutes: 10
    continueOnError: boolean  # 'true' if future jobs should run even if this job fails; defaults to 'false'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - bash: echo "Hello world"

  - job: B
    steps:
    - bash: echo "B"

- stage: B
  jobs:
  - job: B1
  - job: B2