# API Gateway

## Overview

API Gateway lets you deploy HTTP APIs. It comes in two versions:

- `v1`, also called REST API
- `v2`, also called HTTP API, which is faster and cheaper than `v1`


## API key

You can secure your Lambda functions with API key.

You can specify a list of API keys in `provider.apiGateway.apiKeys`.

You need to explicitly specify which endpoints are private and require one of the api keys to be included in the request by setting `functions.{function name}.events.http.private` to `true`.

Make sure your API key contains a stage variable if your service has different stages.

You can optionally define usage plan quota and throttle, using `usagePlan` object.

Once you deploy your service, the value of those API keys will be auto generated by AWS and printed on the screen for you to use.

Clients connecting will then need to set API keys values in the `x-api-key` header. This is only necessary for functions where the private property is set to `true`.

```yml
service: python-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  apiGateway:
    apiKeys:
      - myFirstKey:
          - freekey
    usagePlan:
      - myFirstKey:
          quota:
            limit: 5000
            offset: 2
            period: MONTH
          throttle:
            burstLimit: 200
            rateLimit: 100


functions:
  myFunction:
    handler: app.main.lambda_handler  # The lambda handler named `lambda_handler` is defined in `app/main.py`
    events:
      - http:
          method: GET
          path: /
          private: true   # can only be called with API key
```


## References

- [REST API (API Gateway v1)](https://www.serverless.com/framework/docs/providers/aws/events/apigateway)
- [REST API vs. HTTP API](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html)