# Amazon CloudWatch

## Overview

Amazon CloudWatch is a monitoring service for AWS cloud resources and the applications you run on AWS.

CloudWatch is used to collect and track metric, set alarms, collect, and monitor log files from AWS and non- AWS sources.

CloudWatch Alarms monitor metrics and can be configured to automatically initiate actions.

CloudWatch Logs centralizes logs from systems, applications, and AWS services.

CloudWatch Events delivers a stream of system events that describe changes in AWS resources.

With CloudWatch you can monitor resources such as:
- EC2 instances.
- DynamoDB tables.
- RDS DB instances.
- Custom metrics generated by applications and services.
- Any log files generated by your applications.

Use cases:
- Visualize logs and metrics with the AWS Management Console.
- Discover insights to keep your applications healthy.
- Troubleshoot issues.
- Set alarms to alert you when something's not right.
- Detect anomalous behavior in your environments.
- Take automated actions like scaling.

![](https://digitalcloud.training/wp-content/uploads/2022/01/amazon-cloudwatch-service-and-features.jpeg)


## CloudWatch Dashboards

The CloudWatch dashboard feature enables you to access all the metrics for your resources from a single location. 

You can pull data from different Regions into a single dashboard in order to create a global view of your architecture.

> For example, you can use a CloudWatch dashboard to monitor the CPU utilization of an Amazon EC2 instance, the total number of requests made to an Amazon S3 bucket, and more.
>
> You can even customize separate dashboards for different business purposes, applications, or resources.


## Container Insights

**Container Insights** allows you to collect, aggregate, and summarize metrics and logs from your containerized applications.

Can be used for containers running on Amazon ECS, Amazon EKS, and K8s platforms on Amazon EC2. 

Also provides diagnostic information: container restart failures, to help you isolate issues and resolve them quickly.

It collects data as performance log events (JSON) using embedded metric format. From this data, CloudWatch creates aggregated metrics at the cluster, node, pod, task, and service level as CloudWatch metrics.

Metrics are available in CloudWatch automatic dashboards, viewable in the Metrics section of the CloudWatch console.

Metrics includes: CPU, memory, disk, network. 

Can set CloudWatch alarms on collected metrics. 


## CloudWatch vs CloudTrail

| CloudWatch | CloudTrail |
|---|---|
| Performance monitoring | Auditing |
| Log events across AWS Services (operations) | Log API activity across AWS services (activities, or actor) |
| Higher-level comprehensive monitoring and event service | More low-level, granular |
| Log from multiple accounts | Log from multiple accounts |
| Logs stored indefinitely | Logs stored to S3 or CloudWatch indefinitely |
| Alarms history for 14 days | No native alarming; can use CloudWatch alarms |
