# Encryption

## Overview

You can encrypt both the boot and data volumes of an EC2 instance.

When you encrypt an EBS volume:
- data inside the volume is encrypted
- data moving between instance and volume is encrypted
- snapshots are encrypted
- volumes created from snapshots are encrypted

Encrypted volumes has the same IOPS performance as unencrypted volumes.

Encryption has a minimal impact on larency. You won't get any performance degradation.

You can encrypt root device volume upon creation.


## Data Key

The data key is used to encrypt and decrypt data stored on the EBS volume (AES-256 standard).

The data key is generated by AWS KMS and then encrypted with your CMK, prior to being stored with your volume information.

The same data key is shared by snapshots of the volume and any subsequent volumes created from those snapshots.


## Encryption Key

The encryption key is used to encrypt and decrypt the data key.

Encryption keys are customer managed keys (CMK), and they are managed by the AWS KMS.

A default CMK key is generated for the first encrypted volumes.

Subsequent encrypted volumes will use their own unique key (AES 256 bit).

The CMK used to encrypt a volume is used by any snapshots and volumes created from snapshots.


## Encrypting volumes

Steps to encrypt a volume:
- create a snapshot of unencrypted volume
- copy the snapshot with encryption enabled
- create an AMI from the encrypted snapshot
- use that AMI to launch new instances

You can check the encryption status of your EBS volumes with AWS Config.

You can **unencrypt a volume** by copying it to a unencrypted volume using a temporary EC2 instance. You can then attach the unencrypted volume to your original instance.


## Snapshot

You can allow encryption when copying an unencrypted snapshot.

Snapshots of encrypted volumes are encrypted automatically.

You can share encrypted snapshots with other AWS accounts if it is encrypted with a custom CMK key.

You cannot make encrypted snapshots public.

You can share unencrypted snapshots with other AWS accounts by making them private and selecting the accounts to share them with.

You can share unencrypted snapshots with the AWS community by making them public.


## Sharing volumes

You cannot share encrypted volumes created using a default CMK key.

You cannot change the CMK key that is used to encrypt a volume.

To share an encrypted volume:
- create an snapshot of the volume in the source account
- share the snapshot with the target account
- create a copy of the shared snapshot and change encryption keys as part of the copy in the target account.
