# FastAPI Overview

## Version

This document is for FastAPI v0.110.0.


## Overview

FastAPI is a Python web framework. It helps building web applications, especially web APIs.

More modern than most Python web frameworks, taking advantage of features added to Python 3 in the last few year.

**Advantages**:
- Performance: As fast as Node.js and Go in some cases, unusual for Python frameworks.
- Faster development
- Better code quality: Type hinting and models help reduce bugs.
- Autogenerated documentation and test pages: Much easier than hand-editing OpenAPI descriptions.
- Use Python type hints
- Support asynchronous communication


## Requirements

Python 3.10+


## Installation

Install FastAPI framework:

```sh
pip install fastapi==0.110.0
```

Install Uvicorn web server:

```sh
pip install uvicorn
```
