name: Deploy Rspress site to Github Pages

on:
  pull_request:
    branches: main

  push:
    branches: main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Not needed if lastUpdated is not enabled

    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.12.3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install  # --frozen-lockfile option will be automatically added if you run it on CI

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Build with Rspress
      run: pnpm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: doc_build

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4